import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import SearchBar from '../src/components/searchBar'
import { getCommits, getRepos } from '../src/api'
import { Repository } from '../src/models/repository.model'
import { Commit } from '../src/models/commit.model'
import List from '../src/components/list'



export default function Home() {
  const [user, setUser] = useState<string>();
  const [repos, setRepos] = useState<Repository[]>();
  const [loading, setLoading] = useState(false);
  const [repo, setRepo] = useState<Repository>();
  const [commits, setCommits] = useState<Commit[]>();

  const handleSearch = async (username) => {
    const repositoriesResults = await getRepos(username || "victoraguilerag");
    setRepos(repositoriesResults);
    setUser(username || "victoraguilerag")
  }

  const handleSearchCommits = async () => {
    console.log(user)
    const repositoriesResults = await getCommits(repo.name || "aerolab-challenge", user);
    setCommits(repositoriesResults);
  }

  const handleLoad = () => {
    setLoading(true);
  }

  useEffect(() => {
    if (!!repo) handleSearchCommits()
  }, [repo])
 
  useEffect(() => {
    if (!loading) handleLoad()
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>Title</p>
        <SearchBar onSearch={handleSearch} />
        <div className={styles.tags}>
          {repo && <div className={styles.stag}>{repo.name}</div>}
        </div>
        {repos && !repo && <List items={repos} onClick={setRepo} />}
        {!!commits && <List items={commits} onClick={setRepo} />}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
